### ISSUE TITLE
Add option to export Power

### ISSUE THREAD

**Issue by ieRev** [M-Yankov/TelemetryExporter#38]
Hi
Could you please add the option to export Power levels, with graph and text options, similar to speed.

Thanks
Derek

**Comment by M-Yankov** [comment]
Can you attach a `.FIT` file, containing such data? 
I don't have electronics attached on my bikes in that garmin can take data from them. 
And also some example picture or video if you have

**Comment by ieRev** [comment]
[16910207192.zip](https://github.com/user-attachments/files/17215618/16910207192.zip)
[12805623691.zip](https://github.com/user-attachments/files/17215786/12805623691.zip)

16910207192 has power data from a dual sided power meter
12805623691 is single sided power meter 

I don't have any videos as examples, but it would ideally be the same as the speed graph, except showing Watts rather than km/h

**Comment by M-Yankov** [comment]
Thanks, I will check what data can be extracted from the files

**Comment by M-Yankov** [comment]
@ieRev  Added in Release 0.0.6
![image](https://github.com/user-attachments/assets/35f36897-14d0-4852-acee-bba22fa40516)
